// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwhdFQguN1FtaoSRH_Ib8sNg4WnAeOxQY',
    appId: '1:842459666974:web:5454c74b074677a5746c0f',
    messagingSenderId: '842459666974',
    projectId: 'crypto-list-app-ba9ae',
    authDomain: 'crypto-list-app-ba9ae.firebaseapp.com',
    storageBucket: 'crypto-list-app-ba9ae.appspot.com',
    measurementId: 'G-S5H1EVMDPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrwcsXSJb2vk7CWvQ0ArcSRairGfUqLuo',
    appId: '1:842459666974:android:499b33fdcbd02784746c0f',
    messagingSenderId: '842459666974',
    projectId: 'crypto-list-app-ba9ae',
    storageBucket: 'crypto-list-app-ba9ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpMLFw1XQZQI9TvYLk5rZtSl-JeuP61U',
    appId: '1:842459666974:ios:33045bdda201e73b746c0f',
    messagingSenderId: '842459666974',
    projectId: 'crypto-list-app-ba9ae',
    storageBucket: 'crypto-list-app-ba9ae.appspot.com',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpMLFw1XQZQI9TvYLk5rZtSl-JeuP61U',
    appId: '1:842459666974:ios:33045bdda201e73b746c0f',
    messagingSenderId: '842459666974',
    projectId: 'crypto-list-app-ba9ae',
    storageBucket: 'crypto-list-app-ba9ae.appspot.com',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwhdFQguN1FtaoSRH_Ib8sNg4WnAeOxQY',
    appId: '1:842459666974:web:b93a980269d8c02a746c0f',
    messagingSenderId: '842459666974',
    projectId: 'crypto-list-app-ba9ae',
    authDomain: 'crypto-list-app-ba9ae.firebaseapp.com',
    storageBucket: 'crypto-list-app-ba9ae.appspot.com',
    measurementId: 'G-4J0FP2PKGS',
  );
}
